name: Test

on:
  push:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT_MINUTES) }}
    strategy:
      matrix:
        go-version: [1.21, 1.22, 1.23, 1.24, 1.25]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Checkout code
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run unit tests
        run: go test -v ./...
